'Привет java!'
var mything, greeting, numbernine,stringnine,myname,name_orz,num_orz_week,num_orz_mo,num_orz_tu,num_orz_we,num_orz_th,num_orz_fr,num_orz_sa,num_orz_su,name_vet,num_vet_week,num_vet_mo,num_vet_tu,num_vet_we,num_vet_th,num_vet_fr,num_vet_sa,num_vet_su;
mything=5;
mything="Эта строка";
 numbernine = 9;
stringnine ="9";
numbernine + numbernine;
stringnine + stringnine;
greeting = "Привет, ";
myname = "Ник";
greeting + myname;
myname.length;
name_orz= "ОРЗ";
num_orz_mo=2;
num_orz_tu=3;
num_orz_we=2;
num_orz_th=2;
num_orz_fr=3;
num_orz_sa=1;
num_orz_su=2;
num_orz_week=num_orz_mo+num_orz_tu+num_orz_we+num_orz_th+num_orz_fr+num_orz_sa+num_orz_su;
name_vet= "Ветрянка";
num_vet_mo=1;
num_vet_tu=4;
num_vet_we=2;
num_vet_th=0;
num_vet_fr=0;
num_vet_sa=2;
num_vet_su=1;
num_vet_week=num_vet_mo+num_vet_tu+num_vet_we+num_vet_th+num_vet_fr+num_vet_sa+num_vet_su;
name_orz + num_orz_week +" , "+ name_vet + num_vet_week;